<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-TJ2PMSNK" failures="1" tests="9" name="com.qa.testcases.CartPageTest" time="167.302" errors="0" timestamp="2020-08-26T22:57:49 IST" skipped="0">
  <testcase classname="com.qa.testcases.CartPageTest" name="verifyCourseCountTest" time="18.445">
    <failure message="expected [5] but found [5]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [5] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at com.qa.pages.CartPage.verifyCourseCount(CartPage.java:63)
at com.qa.testcases.CartPageTest.verifyCourseCountTest(CartPageTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCourseCountTest -->
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="captureBaseAmountTest" time="19.119"/>
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="captureAmountPayableTest" time="19.612"/>
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="clickOnViewDetailsTest" time="17.911"/>
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="clickOnRemoveTest" time="18.888"/>
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="clickOnApplyCouponTest" time="18.849"/>
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="verifyErrorMessageTest" time="18.879"/>
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="clickOnCloseCouponTest" time="17.525"/>
  <system-out/>
  <testcase classname="com.qa.testcases.CartPageTest" name="clickOnLogoutTest" time="18.074"/>
  <system-out/>
</testsuite> <!-- com.qa.testcases.CartPageTest -->
